#!/usr/bin/env node

const { spawn } = require('child_process');

console.log("Running Webpack, Mocha will run after first successful build")
const pack = spawn('webpack', {
  stdio: ['ignore', 'pipe', 'inherit']
})
pack.stdout.setEncoding('utf-8')

let MOCHA_STARTED = false
pack.stdout.on('data', function (data) {
  if (MOCHA_STARTED) {
    return
  } else if (data.includes('compiled successfully')) {
    spawn('mocha', ['inspect',
                    '--require', 
                    'source-map-support/register', 
                    './dist/test.bundle.js'], {
      stdio: 'inherit'
    })
    MOCHA_STARTED = true
  } else {
    console.log(data)
  }
})